

server:
  port: 3335
spring:
  application:
    name: service-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5000/eureka/

zuul:
  routes:
    api-a:
      path: /provider/**
      serviceId: HI-PROVIDER
    api-b:
      path: /api-b/**
      serviceId: service-feign
